In [1]:
import numpy as np
a=np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [12]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
print('vectorized version'+str(1000*(toc-tic))+'ms')
print(c)

vectorized version0.92315673828125ms
250240.58773233785


In [13]:
c=0
tic=time.time()
# c=np.dot(a,b)
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print('regular'+str(1000*(toc-tic))+'ms')
print(c)

regular652.3609161376953ms
250240.58773233875


In [20]:
a=np.random.randn(5,1)

In [24]:
a.shape

(5, 1)

In [22]:
a.T

array([[ 1.13713736,  1.03640471, -1.04093589,  0.11224073, -0.69795092]])

In [23]:
np.dot(a,a.T)

array([[ 1.29308139,  1.17853452, -1.18368709,  0.12763312, -0.79366607],
       [ 1.17853452,  1.07413472, -1.07883086,  0.11632682, -0.72335962],
       [-1.18368709, -1.07883086,  1.08354753, -0.1168354 ,  0.72652216],
       [ 0.12763312,  0.11632682, -0.1168354 ,  0.01259798, -0.07833852],
       [-0.79366607, -0.72335962,  0.72652216, -0.07833852,  0.48713548]])

In [27]:
a=np.random.randn(4,3) 
b=np.random.randn(3,2)
c=a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [26]:
c

array([[3.46697065, 1.62195106],
       [0.07360902, 3.14914441],
       [0.09300326, 0.14759475]])